### ISSUE TITLE
Viet Nam or Vietnam

### ISSUE THREAD

**Issue by Scattered-Thoughts** [lukes/ISO-3166-Countries-with-Regional-Codes#19]
I found that Vietnam is spelled as  Viet Nam 

Researching it Vietnam is the western/English spelling and Việt Nam not Viet Nam the Vietnamese spelling

Happy to change this manually in all files if wanted?

**Comment by lukes** [comment]
Thanks for your issue, and sorry for the delay in replying. 

This is a difficult one. I don't manually edit the names of countries, instead, I defer to the correctness of the ISO-3166 standard. 

The standard has the country name as Viet Nam.

You can see this in both of my two sources:

https://en.wikipedia.org/wiki/ISO_3166-1
https://unstats.un.org/unsd/methodology/m49/

The country names are clearly the English versions (e.g. Germany and not Deutschland). So perhaps you'd expect the name to be Vietnam, but ... that's what it is in the ISO-3166 standard, so that's what my data will present.

Thanks for raising this though.

Feel free to fork this repository and fix it to whatever you like personally, and refer to your fork for your own projects. I suspect this is why this repo has been forked 721 times at time of writing :).
