### ISSUE TITLE
Swaziland king renames country 'the Kingdom of eSwatini'

### ISSUE THREAD

**Issue by adrianyorke** [lukes/ISO-3166-Countries-with-Regional-Codes#21]
Firstly, thanks for a great repo and thanks for keeping it up to date and accurate.

Now the news: King Mswati III of Swaziland has announced that he is renaming the country "the Kingdom of eSwatini" - he's been calling it that for years apparently. 

More info here:
http://www.bbc.com/news/world-africa-43821512

Happy to submit a pull request if you need help updating but I see you like to do this yourself with previous changes.

**Comment by lukes** [comment]
Thanks, I'm happy to maintain it! 

We'll have to wait until the name change comes through into the iso-3166 specification since this repo is a reflection of the iso-3166 data. I've checked and Swaziland's name change hasn't yet - it may be some time before the change makes it. I'll keep this issue open for as long as you're happy to have it open too, and will revisit the issue periodically.

Luke

**Comment by adrianyorke** [comment]
Sure, good plan.  Keep up the good work and thanks again.

**Comment by eskimodev** [comment]
Hi guys, the name change seems to be final. See the sources in the comment of my pull request: https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/pull/25

**Comment by lukes** [comment]
Thanks @eskimodev indeed you're correct.  I'll refresh all 9 data sets with the new name.
